#include<stdio.h>
#include<stdlib.h>
#include<string.h>
#include<time.h>
int easy();
int medium ();
int hard();
int main()
{

printf("\n(:- This is a singleplayer number guessing game. Here system will generate a random number in background and you have to guess that number generated by system. -:)\n");
printf("!! Number generating system is totaly ramdom !!\n");


printf("\nChoose the leval of game :\n");
printf("1 for easy\n");
printf("2 for medium\n");
printf("3 for hard\n");
printf("~");

int leval,z;
scanf("%d",&leval);


if (leval == 1){

   easy();

}
else if (leval == 2){
   medium();
}
else if (leval == 3){
    
   hard();
}
else {
    printf ("please enter a valid input");
}

return 0;
}


// function of game
int easy ()
{
int a,num,x=1;
srand(time(0));
a=rand()%10 + 1;
printf("\nGuess the number between 1 to 10:");
do {

scanf ("%d",&num);
if (num<a){
    printf("\nGuess any higher number please:");
}
else if (num>a){
    printf("\nGuess any lower number please:");
}
else {
    printf("\n-----You guess the number in :%d attemp-----\n",x);
}
x++;
}

while(num!=a);
} 

int medium (){
int a,num,x=1;
srand(time(0));
a=rand()%40 + 1;
printf("\nGuess the number between 1 to 40:");
do {

scanf ("%d",&num);
if (num<a){
    printf("\nGuess any higher number please:");
}
else if (num>a){
    printf("\nlGuess any ower number please:");
}
else {
    printf("\n-----You guess the number in :%d attemp-----\n",x);
}
x++;

}
while(num!=a);
} 

int hard (){
int a,num,x=1;
srand(time(0));
a=rand()%100 + 1;
printf("\nGuess the number between 1 to 100:");
do {

scanf ("%d",&num);
if (num<a){
    printf("\nGuess any higher number please:");
}
else if (num>a){
    printf("\nGuess any lower number please:");
}
else {
    printf("\n-----You guess the number in :%d attemp-----\n",x);
}
x++;
}
while(num!=a);
}
